# .github/workflows/ci.yml
name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install and build the client application
      - name: Install client dependencies
        run: npm install
        working-directory: Hospital-Management-System/client

      - name: Build client application
        run: npm run build
        working-directory: Hospital-Management-System/client

      # Install the server dependencies
      - name: Install server dependencies
        run: npm install
        working-directory: Hospital-Management-System/server

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install client dependencies
        run: npm install
        working-directory: Hospital-Management-System/client

      - name: Build client application
        run: npm run build
        working-directory: Hospital-Management-System/client

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Hospital-Management-System/client/build
